### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by orhun** [glicol/glicol-cli#14]
Hey!

I'm getting the following error on `glicol-cli` launch:

![capture](https://p.orhun.dev/4o4qLr.png)

Then my terminal gets corrupted.

It points to this line (`131`):

https://github.com/glicol/glicol-cli/blob/c5f6493a6dac0f9ff65b59179f6c7c5b65fa4fce/src/main.rs#L127-L133

Not sure why it happens but is it related to my audio device? Any help is appreciated.

P.S. I'm using `test.glicol` from this repository.

**Comment by chaosprint** [comment]
Should be fixed with the latest commit:

https://github.com/glicol/glicol-cli/commit/1bf5176e905a12e988bae9f7a3d1256e641d1e81

Do you manage to get the sound working?

**Comment by orhun** [comment]
Yup, works really well! Thanks. 🐻
