### ISSUE TITLE
"samples" example from glicol.org/tour causes ERROR: "cannot use this non-exist samples" 

### ISSUE THREAD

**Issue by hobo1618** [glicol/glicol-cli#32]
Love the library!

I'm running glicol-cli on Ubuntu 22.04 with neovim as my text-editor. 
The samples don't appear to load properly and I can't figure out how I would run `addSampleFolder()` or similar since I'm not running glicol in the browser. I downloaded the zip folder with all the samples but not sure how to load them in locally, in other words. 

```
// test.glicol
out: imp 1.0 >> sp \808bd
```

Here is the full error:

```console
ERROR glicol_cli: get next block of engine: cannot use this non-exist samples \808bd
```

I tried a few different samples from the list but no dice.

Any help would be much appreciated!

**Comment by chaosprint** [comment]
you can try to download and unzip this repo:

https://github.com/chaosprint/glicol

Find the path of the `./js/assets`, e.g. `/Users/SOMEUSERNAME/Downloads/glicol-main/js/assets/`


```sh
expor GLICOL_CLI_SAMPLES_PATH=/Users/SOMEUSERNAME/Downloads/glicol-main/js/assets/
```

Then you can run:

`glicol-cli test.glicol`:

```
// test.glicol
out: imp 1.0 >> sp \808bd
```

**Comment by hobo1618** [comment]
worked, thank you!
