### ISSUE TITLE
Panic at head when running in dev mode

### ISSUE THREAD

**Issue by capslock** [glicol/glicol-cli#8]
Fresh clone, just a bare `cargo run` at head panics:

```shell
% cargo run -- 1.glicol
warning: unused import: `Sample`
  --> src/main.rs:10:17
   |
10 |     FromSample, Sample, SizedSample,
   |                 ^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `glicol-cli` (bin "glicol-cli") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/glicol-cli 1.glicol`
thread 'main' panicked at 'Argument 'file' is a positional argument and can't have short or long name versions', /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/debug_asserts.rs:731:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like this is in dev mode only -- `cargo run --release` works fine.

<details><summary>Full backtrace</summary>
<p>
<pre>
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: clap::builder::debug_asserts::assert_arg
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/debug_asserts.rs:731:9
   3: clap::builder::debug_asserts::assert_app
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/debug_asserts.rs:61:9
   4: clap::builder::command::Command::_build_self
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:3920:13
   5: clap::builder::command::Command::_do_parse
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:3790:9
   6: clap::builder::command::Command::try_get_matches_from_mut
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:708:9
   7: clap::builder::command::Command::get_matches_from
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:578:9
   8: clap::builder::command::Command::get_matches
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/builder/command.rs:490:9
   9: clap::derive::Parser::parse
             at /Users/rich/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.8/src/derive.rs:82:27
  10: glicol_cli::main
             at ./src/main.rs:53:16
  11: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5

</pre>
</p>
</details>

**Comment by chaosprint** [comment]
thanks for reporting this. now it should be fixed with: https://github.com/glicol/glicol-cli/commit/238fa747fbd71b68ae5e9baa8739337e8c3b9219
