### ISSUE TITLE
[Bug] optional dependency `jack` is not included in any feature

### ISSUE THREAD

**Issue by Jeansidharta** [glicol/glicol-cli#9]
Hi!

I just tried to install `glicol-cli`, with the command in the README:

```
cargo install --git https://github.com/glicol/glicol-cli.git
```

and was greeted with this error:
```
    Updating git repository `https://github.com/glicol/glicol-cli.git`
error: failed to parse manifest at `/home/XXXXX/.cargo/git/checkouts/glicol-cli-b10f0cfdae7f5c00/d3f80b8/Cargo.toml`

Caused by:
  optional dependency `jack` is not included in any feature
  Make sure that `dep:jack` is included in one of features in the [features] table.
```

I noticed there was a commit 13 hours ago adding jack as an optional dependency. Maybe it was related?

**Comment by Jeansidharta** [comment]
Installing the previous commit using `cargo install --git https://github.com/glicol/glicol-cli.git --rev 238fa747fbd71b68ae5e9baa8739337e8c3b9219` worked

**Comment by chaosprint** [comment]
It should be fine now. Are you using Mac?

**Comment by Jeansidharta** [comment]
Yep. It's working now. Thanks :)

And no, I'm running Arch Linux 6.0.12

**Comment by chaosprint** [comment]
> Yep. It's working now. Thanks :)
> 
> And no, I'm running Arch Linux 6.0.12

Is the sound also working?
